In [ ]:
import pandas as pd

dados=pd.read_csv('tracks_features.csv')
dados=dados.dropna() #Para excluir valores nulos
display(dados.describe())

In [ ]:
import pandas as pd

arquivo=pd.read_csv("tracks_features.csv", sep=",", encoding="latin-1") #caminhos dos arquivos

display(arquivo.head())

In [ ]:
import polars as pl

arquivo=pl.read_csv("tracks_features.csv", separator=",", encoding="latin-1") #caminhos dos arquivos

display(arquivo.head())

In [8]:
import pandas as pd
import polars as pl
import pyarrow as pa
import pyarrow.parquet as pq
import os

In [3]:
arquivo_csv = 'tracks_features.csv'
arquivo_parquet = 'tracks_features.csv_POLARS.parquet'

# 1. scan_csv() apenas cria o plano (LazyFrame)
lazy_query = pl.scan_csv(arquivo_csv, separator=',', encoding='utf8-lossy')

# 2. sink_parquet() executa o plano em modo streaming
#    e salva o resultado direto no disco.
lazy_query.sink_parquet(arquivo_parquet)

print(f"Arquivo '{arquivo_csv}' convertido para '{arquivo_parquet}' com sucesso!")

Arquivo 'tracks_features.csv' convertido para 'tracks_features.csv_POLARS.parquet' com sucesso!

In [13]:
import polars as pl
import time

# 1. Modo Lazy: Estamos apenas escaneando o arquivo, sem carregar para a RAM
# scan_parquet já inicia em modo lazy por padrão.
q = (
    pl.scan_parquet("tracks_features.csv_POLARS.parquet")
    .filter(pl.col("explicit") == True)
)

print(type(q)) # Note que é um LazyFrame, não um DataFrame
print("\n")

# 2. O Plano de Execução (Explain)
print("--- Plano de Execução (Explain) ---")
print("O Polars analisou sua query e otimizou o caminho antes de tocar nos dados:")
print(q.explain())
print("\n")

# 3. Execução Real (Collect)
print("--- Executando (Collect) ---")
start_time = time.time()
df_resultado = q.collect()
end_time = time.time()

display(df_resultado)

<class 'polars.lazyframe.frame.LazyFrame'>


--- Plano de Execução (Explain) ---
O Polars analisou sua query e otimizou o caminho antes de tocar nos dados:
Parquet SCAN [tracks_features.csv_POLARS.parquet]
PROJECT */24 COLUMNS
SELECTION: [(col("explicit")) == (true)]
ESTIMATED ROWS: 1204025


--- Executando (Collect) ---

shape: (82_648, 24)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ id         ┆ name       ┆ album      ┆ album_id   ┆ … ┆ duration_ ┆ time_sign ┆ year ┆ release_d │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ms        ┆ ature     ┆ ---  ┆ ate       │
│ str        ┆ str        ┆ str        ┆ str        ┆   ┆ ---       ┆ ---       ┆ i64  ┆ ---       │
│            ┆            ┆            ┆            ┆   ┆ i64       ┆ f64       ┆      ┆ str       │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ 1wsRitfRRt ┆ Guerrilla  ┆ The Battle ┆ 2eia0myWFg ┆ … ┆ 206200    ┆ 4.0       ┆ 1999 ┆ 1999-11-0 │
│ WyEapl0q22 ┆ Radio      ┆ Of Los     ┆ oHuttJytCx ┆   ┆           ┆           ┆      ┆ 2         │
│ o8         ┆            ┆ Angeles    ┆ gX         ┆   ┆           ┆           ┆      ┆           │
│ 2lbASgTSoD ┆ Mic Check  ┆ The Battle ┆ 2eia0myWFg ┆ … ┆ 213640    ┆ 4.0       ┆ 1999 ┆ 1999-11-0 │
│ O7MTuLAXlT ┆            ┆ Of Los     ┆ oHuttJytCx ┆   ┆           ┆           ┆      ┆ 2         │
│ W0         ┆            ┆ Angeles    ┆ gX         ┆   ┆           ┆           ┆      ┆           │
│ 7o2Razxnl3 ┆ Ashes In   ┆ The Battle ┆ 2eia0myWFg ┆ … ┆ 277267    ┆ 4.0       ┆ 1999 ┆ 1999-11-0 │
│ 3Jrgz4PpMY ┆ the Fall   ┆ Of Los     ┆ oHuttJytCx ┆   ┆           ┆           ┆      ┆ 2         │
│ Na         ┆            ┆ Angeles    ┆ gX         ┆   ┆           ┆           ┆      ┆           │
│ 6ZU9RJIZ0f ┆ Bombtrack  ┆ Rage       ┆ 4LaRYkT4oy ┆ … ┆ 243760    ┆ 4.0       ┆ 1992 ┆ 1992-11-0 │
│ NaFuQM57bD ┆            ┆ Against    ┆ 47wEuQgkLB ┆   ┆           ┆           ┆      ┆ 3         │
│ IA         ┆            ┆ The        ┆ ul         ┆   ┆           ┆           ┆      ┆           │
│            ┆            ┆ Machine    ┆            ┆   ┆           ┆           ┆      ┆           │
│ 3FUS56gKr9 ┆ Killing In ┆ Rage       ┆ 4LaRYkT4oy ┆ … ┆ 313667    ┆ 4.0       ┆ 1992 ┆ 1992-11-0 │
│ mVBmzvlnod ┆ the Name   ┆ Against    ┆ 47wEuQgkLB ┆   ┆           ┆           ┆      ┆ 3         │
│ lh         ┆            ┆ The        ┆ ul         ┆   ┆           ┆           ┆      ┆           │
│            ┆            ┆ Machine    ┆            ┆   ┆           ┆           ┆      ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …    ┆ …         │
│ 26w9NTiE9N ┆ BOOKER T   ┆ EL ÚLTIMO  ┆ 2d9BCZeAAh ┆ … ┆ 156430    ┆ 4.0       ┆ 2020 ┆ 2020-11-2 │
│ GjW1ZvIOd1 ┆            ┆ TOUR DEL   ┆ iZWPpbX9aP ┆   ┆           ┆           ┆      ┆ 7         │
│ So         ┆            ┆ MUNDO      ┆ CW         ┆   ┆           ┆           ┆      ┆           │
│ 67ACYA3UI6 ┆ LA DROGA   ┆ EL ÚLTIMO  ┆ 2d9BCZeAAh ┆ … ┆ 162299    ┆ 4.0       ┆ 2020 ┆ 2020-11-2 │
│ QMNtHX6b34 ┆            ┆ TOUR DEL   ┆ iZWPpbX9aP ┆   ┆           ┆           ┆      ┆ 7         │
│ wX         ┆            ┆ MUNDO      ┆ CW         ┆   ┆           ┆           ┆      ┆           │
│ 4MzXwWMhyB ┆ DÁKITI     ┆ EL ÚLTIMO  ┆ 2d9BCZeAAh ┆ … ┆ 205090    ┆ 4.0       ┆ 2020 ┆ 2020-11-2 │
│ bmu6hOcLVD ┆            ┆ TOUR DEL   ┆ iZWPpbX9aP ┆   ┆           ┆           ┆      ┆ 7         │
│ 49         ┆            ┆ MUNDO      ┆ CW         ┆   ┆           ┆           ┆      ┆           │
│ 5jZ32WOU7s ┆ SORRY PAPI ┆ EL ÚLTIMO  ┆ 2d9BCZeAAh ┆ … ┆ 163053    ┆ 4.0       ┆ 2020 ┆ 2020-11-2 │
│ qzDYbzINwM ┆            ┆ TOUR DEL   ┆ iZWPpbX9aP ┆   ┆           ┆           ┆      ┆ 7         │
│ Uk         ┆            ┆ MUNDO      ┆ CW         ┆   ┆           ┆           ┆      ┆           │
│ 3KJ3opyV29 ┆ 120        ┆ EL ÚLTIMO  ┆ 2d9BCZeAAh ┆ … ┆ 151506    ┆ 4.0       ┆ 2020 ┆ 2020-11-2 │
│ 269SXkPrc1 ┆            ┆ TOUR DEL   ┆ iZWPpbX9aP ┆   ┆           ┆           ┆      ┆ 7         │
│ 9l         ┆            ┆ MUNDO      ┆ CW         ┆   ┆           ┆           ┆      ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

In [11]:
analise_danceability = (
    pl.scan_parquet("tracks_features.csv_POLARS.parquet")        

    .group_by("danceability")
    .agg([
        pl.col("duration_ms").mean().alias("valor_medio"),
        pl.col("duration_ms").count().alias("total_duracao")
    ])
    .sort("valor_medio", descending=True)
)

display(analise_danceability.collect())

shape: (1_362, 3)
┌──────────────┬───────────────┬───────────────┐
│ danceability ┆ valor_medio   ┆ total_duracao │
│ ---          ┆ ---           ┆ ---           │
│ f64          ┆ f64           ┆ u32           │
╞══════════════╪═══════════════╪═══════════════╡
│ 0.0529       ┆ 3.263e6       ┆ 1             │
│ 0.0556       ┆ 838677.0      ┆ 3             │
│ 0.0551       ┆ 837699.4      ┆ 5             │
│ 0.0575       ┆ 730016.166667 ┆ 6             │
│ 0.073        ┆ 693734.947368 ┆ 19            │
│ …            ┆ …             ┆ …             │
│ 0.0507       ┆ 77427.0       ┆ 1             │
│ 0.0516       ┆ 76227.0       ┆ 1             │
│ 0.0484       ┆ 56000.0       ┆ 1             │
│ 0.0          ┆ 44487.583153  ┆ 2778          │
│ 0.0449       ┆ 32533.0       ┆ 1             │
└──────────────┴───────────────┴───────────────┘